Link to the Dataset and Description

https://archive.ics.uci.edu/ml/datasets/Combined+Cycle+Power+Plant#

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00294/CCPP.zip
!unzip *.zip

--2021-05-13 18:24:55--  https://archive.ics.uci.edu/ml/machine-learning-databases/00294/CCPP.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3674852 (3.5M) [application/x-httpd-php]
Saving to: ‘CCPP.zip’

CCPP.zip            100%[===================>]   3.50M  8.37MB/s    in 0.4s    

2021-05-13 18:24:56 (8.37 MB/s) - ‘CCPP.zip’ saved [3674852/3674852]

Archive:  CCPP.zip
   creating: CCPP/
  inflating: CCPP/Folds5x2_pp.ods    
  inflating: CCPP/Folds5x2_pp.xlsx   
  inflating: CCPP/Readme.txt         
  inflating: CCPP/Readme.txt~        


In [ ]:
!ls
%cd CCPP 

CCPP  CCPP.zip	sample_data
/content/CCPP


In [ ]:
%pwd

'/content/CCPP'

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
df = pd.read_excel('Folds5x2_pp.xlsx')
print(f"The shape of the dataset is - {df.shape}")

The shape of the dataset is - (9568, 5)


In [ ]:
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [ ]:
df.describe()

AT            V           AP           RH           PE
count  9568.000000  9568.000000  9568.000000  9568.000000  9568.000000
mean     19.651231    54.305804  1013.259078    73.308978   454.365009
std       7.452473    12.707893     5.938784    14.600269    17.066995
min       1.810000    25.360000   992.890000    25.560000   420.260000
25%      13.510000    41.740000  1009.100000    63.327500   439.750000
50%      20.345000    52.080000  1012.940000    74.975000   451.550000
75%      25.720000    66.540000  1017.260000    84.830000   468.430000
max      37.110000    81.560000  1033.300000   100.160000   495.760000

In [ ]:
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values

In [ ]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(Y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,
                                                    Y,
                                                    test_size = 0.2,
                                                    random_state = 42)
print(f"Size of X_train : {X_train.shape}")
print(f"Size of Y_train : {Y_train.shape}")
print(f"Size of X_test : {X_test.shape}")
print(f"Size of Y_test : {Y_test.shape}")

Size of X_train : (7654, 4)
Size of Y_train : (7654,)
Size of X_test : (1914, 4)
Size of Y_test : (1914,)


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=6, activation='relu'))
model.add(tf.keras.layers.Dense(units=6, activation='relu'))
model.add(tf.keras.layers.Dense(units=1))
model.compile(optimizer='adam', loss= 'mean_squared_error')
model.fit(X_train,Y_train,batch_size=32, epochs=100)
model.summary()

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 2119.2371
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 122.0659
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 104.6216
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 86.0242
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 74.5182
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 60.2374
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 54.8020
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 48.8754
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 43.2644
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 41.4313
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 37.8321
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - loss: 35.94

In [ ]:
Y_pred = model.predict(X_test)

In [ ]:
np.set_printoptions(precision=2)
print(np.concatenate((Y_pred.reshape(len(Y_pred), 1), Y_test.reshape(len(Y_test), 1)), 1))

[[455.49 455.27]
 [437.64 436.31]
 [432.48 440.68]
 ...
 [480.05 479.53]
 [434.59 435.76]
 [458.74 457.1 ]]


In [ ]:
print("The Mean Squared Error is: %.2f" % mean_squared_error(Y_test, Y_pred))
print("Variance Score: %.2f" % r2_score(Y_test, Y_pred))

The Mean Squared Error is: 26.13
Variance Score: 0.91
